controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

root:
    path: /
    controller: App\Controller\ArticleController::index
    methods: ['GET']

createArticle:
    path: /article/create
    controller: App\Controller\ArticleController::createArticle
    methods: ['GET', 'POST']

viewArticle:
    path: /article/view/{id}
    controller: App\Controller\ArticleController::viewArticle
    methods: ['GET']

updateArticle:
    path: /article/update/{id}
    controller: App\Controller\ArticleController::updateArticle
    methods: ['GET', 'POST']

deleteArticle:
    path: /article/delete/{id}
    controller: App\Controller\ArticleController::deleteArticle
    methods: ['GET']