<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6oTxsH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6oTxsH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6oTxsH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6oTxsH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6oTxsH\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6oTxsH',
    'container.build_id' => '66a178b4',
    'container.build_time' => 1660658731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6oTxsH');
