<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'root' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/']], [], [], []],
    'slug' => [['slug'], ['_controller' => 'App\\Controller\\ArticleController::slug'], [], [['variable', '/', '[^/]++', 'slug', true]], [], [], []],
];
